//App Users

export const SET_USER_DATA = 'SET_USER_DATA';
export const APP_IS_LOADING = 'APP_IS_LOADING';
export const APP_INITIALIZED = 'APP_INITIALIZED';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const SET_USER_RESET_EMAIL = 'SET_USER_RESET_EMAIL';

//Groups

export const SET_ALL_GROUPS = 'SET_ALL_GROUPS';
export const SET_CURRENT_GROUP = 'SET_CURRENT_GROUP';
export const SET_STUDENTS_GROUP = 'SET_STUDENTS_GROUP';
export const SET_GROUP_LOADING = 'SET_GROUP_LOADING';
